baseurl: "https://haaforever.github.io/blog/"
canonifyURLs: true
publishDir: "docs"
languageCode: "en-us"
title: "Haji blog"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Jihyeon Ha](https://www.instagram.com/hajiboost/) 2020 -- | [Github](https://github.com/haaforever)"

markup:
  goldmark:
    renderer:
      unsafe: true
